title: "LIME – UFRN"
subtitle: "Laboratório de Instrumentação e Microeletrônica"
description: "Official website of LIME at UFRN, focusing on instrumentation, microelectronics, and embedded systems."
header: images/background.jpg
footer: images/background.jpg
proofer: false

# contact and social
links:
  email: lime@ufrn.br
  github: LIME-UFRN
  google-scholar: ETJoidYAAAAJ
  twitter: limeufrn
  youtube: limechannel

# Use Greene Lab template as a remote theme (GitHub-Pages-compatible)
remote_theme: greenelab/lab-website-template

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "members"
    values:
      layout: member
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  members:
    output: true
  posts:
    output: true

sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
